pipeline {
    agent any
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
              echo "hellow World! 2"
            }
        }
        stage('Test') {
            steps {
               echo 'test 2' 
            }
        }
    }
}
