pipeline {
    agent any
    environment {
        CI = 'true'
        changed =  """${sh(
                returnStatus: true,
                script: 'git diff --name-only HEAD~1| cut -d "/" -f1 | uniq | grep 2;exit $?'
            )}"""
    }
    stages {
        stage('Build') {
	when {
		expression { return env.changed }
	}
            steps {
              echo "hellow World!"
            }
        }
        stage('Test') {
            steps {
               echo 'test' 
            }
        }
    }
}
